name: CI

on:
  push:
    branches:
      #- master
  pull_request:

jobs:
  test:
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          # - '3.1'
          # - '3.0'
          - '2.7'
    env:
      IS_TRAVIS: true
      STRIPE_TEST_SECRET_KEY_A: sk_test_BsztzqQjzd7lqkgo1LjEG5DF00KzH7tWKF
      STRIPE_TEST_SECRET_KEY_B: sk_test_rKCEu0x8jzg6cKPqoey8kUPQ00usQO3KYE
      STRIPE_TEST_SECRET_KEY_C: sk_test_qeaB7R6Ywp8sC9pzd1ZIABH700YLC7nhmZ
      STRIPE_TEST_SECRET_KEY_D: sk_test_r1NwHkUW7UyoozyP4aEBD6cs00CI5uDiGq
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Unit tests
      run: |
        bundle exec rspec
    - name: Live tests
      run: |
        bundle exec rspec -t live
